# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

from django.contrib import admin


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$',
        auth_views.login,
        {'template_name': 'login.html'},
        name='login'),
    url(r'^accounts/logout/$',
        auth_views.logout,
        {'next_page': '/accounts/login/'},
        name='logout'),
    url(r'^$',
        'labrador.chuzuwu.views.index',
        name='index'),
    url(r'^money$',
        'labrador.chuzuwu.views.money_index',
        name='money'),
    url(r'^money/add',
        'labrador.chuzuwu.views.money_add',
        name='money_add'),
    url(r'^money/update/(?P<rid>\d+)$',
        'labrador.chuzuwu.views.money_update',
        name='money_update'),
    url(r'^money/record/export/(?P<pid>\d+)$',
        'labrador.chuzuwu.views.download_record',
        name='download_record'),
    # url(r'^money/record/import$',
    #     'labrador.chuzuwu.views.upload_record',
    #     name='import_record'),
    url(r'^tenant$',
        'labrador.chuzuwu.views.tenant_index',
        name='tenant'),
    url(r'^tenant/add$',
        'labrador.chuzuwu.views.tenant_add',
        name='tenant_add'),
    url(r'^tenant/update/(?P<tid>\d+)',
        'labrador.chuzuwu.views.tenant_update',
        name='tenant_update'),
    url(r'^room$',
        'labrador.chuzuwu.views.room_index',
        name='room'),
    url(r'^room/add$',
        'labrador.chuzuwu.views.room_add',
        name='room_add'),
    url(r'^room/update/(?P<rid>\d+)$',
        'labrador.chuzuwu.views.room_update',
        name='room_update'),
    url(r'^room/record$',
        'labrador.chuzuwu.views.room_record',
        name='room_record'),
    url(r'^room/record/add$',
        'labrador.chuzuwu.views.room_record_add',
        name='room_record_add'),
    url(r'^room/record/update/(?P<rid>\d+)$',
        'labrador.chuzuwu.views.room_record_update',
        name='room_record_update'),
    url(r'^statistic/year$',
        'labrador.chuzuwu.views.statistic_year',
        name='statistic_year'),
    url(r'^api/room/enter/(?P<rid>\d+)$',
        'labrador.chuzuwu.views.enter_room',
        name='enter_room'),
    url(r'^api/room/leave/(?P<rid>\d+)$',
        'labrador.chuzuwu.views.leave_room',
        name='leave_room'),
)
